### ISSUE TITLE
When I die, I can't come back to life

### ISSUE THREAD

**Issue by moayad155** [Floris0106/Rereskillable-Rereforked#24] opened 2022-10-10 15:25 UTC
I have a problem that when I die I can't come back to life (and this with mods)

**Comment by alessandriLuca** [comment] 2022-10-18 19:42
same here , forge version 1.18.2

**Comment by Floris0106** [comment] 2022-11-03 16:02
This is a duplicate of #10. Please first search for similar issues to see if someone has already reported a bug, before submitting an issue yourself.

**Closed as not planned by Floris0106** 2022-11-03 16:02 UTC

**Comment by moayad155** [comment] 2022-11-05 10:29
Is there a solution to this problem?
