### ISSUE TITLE
I can't respawn with Scaling Health Mod.

### ISSUE THREAD

**Issue by HikariError** [Floris0106/Rereskillable-Rereforked#23] opened 2022-08-26 09:43 UTC
When I try to respawn using the Scaling Health mod on my 1.18.2 server, I can't do it since I press the button and it lights up again and not even disabling functions of the 2 mods in the serverconfig or in the config will let me, with my only option only restarting the world. I don't understand why it happens, although it could be how xp works in both. I hope you can help me with this problem. (I posted this same issue on Curseforge without reading before. I'm really sorry)

**Comment by xXMolgadoGamer01Xx** [comment] 2022-09-05 18:40
I'm having the same issue with Hardcore Revival and Incapacitated mod (I've tried with both mods and its the same error), my server log says that I'm ticking

**Comment by Floris0106** [comment] 2022-09-10 13:52
Can you both send your log files? Preferrably through something like pastebin that doesnt expire your pastes

**Comment by ChrisClickbait** [comment] 2022-09-12 04:03
Here's my log, @Floris0106 I loaded up a fresh install of Forge and a download of your latest update on 1.18.2 version 2.1.0 no other mods.
I pressed the respawn button a few times and received the same message in the console, leaving me unable to respawn. 
Appreciate your work on the mod, hope this gets fixed soon!

https://paste.ee/p/QDi3y

**Comment by Floris0106** [comment] 2022-09-12 12:36
Yeah, as I suspected, this is the same problem as #10. Sadly, I haven't found the cause for that bug yet, and I don't have much time to work on modding. Closing as duplicate.

**Closed as not planned by Floris0106** 2022-09-12 12:36 UTC
Labels: Bug, Compat, More info needed
