### ISSUE TITLE
Bug Render (1.16.5)

### ISSUE THREAD

**Issue by Samlegamer** [Floris0106/Rereskillable-Rereforked#14] opened 2022-02-13 09:17 UTC
![2022-02-13_10 08 18](https://user-images.githubusercontent.com/83614614/153746679-47b4c1b9-984a-4d21-b382-61ef9942bd0e.png)

**Comment by Floris0106** [comment] 2022-02-13 16:48
Thank you for submitting this, I hadn't noticed it myself. It was caused by a small refactor I did in a recent update, but it's fixed now.

**Closed as completed by Floris0106** 2022-02-13 16:48 UTC
